  version: 'v3'

  services:
    web:
      build:
        context: .
        dockerfile: ./deploy/Dockerfile
      command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
      restart: on-failure
      volumes:
        - static_volume:/home/app/web/staticfiles
      env_file:
        - ./.env
      depends_on:
        - db
    db:
      image: postgres:16.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=hashtag_bot
        - POSTGRES_PASSWORD=hashtag_bot
        - POSTGRES_DB=hashtag_db
      ports:
        - "${DB_PORT:-1338}:5432"
    redis:
      image: "redis"
    celery:
      build:
        context: .
        dockerfile: ./deploy/Dockerfile
      command: celery -A config worker --loglevel=info
      env_file:
        - ./.env
      depends_on:
        - web
    nginx:
      build: ./deploy/nginx
      volumes:
        - static_volume:/home/app/web/staticfiles
      ports:
        - "${NGINX_PORT:-1337}:80"
      depends_on:
        - web

  volumes:
    postgres_data:
    static_volume: