version: 'v3'

services:
  web:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env

  db:
    image: postgres:16.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hashtag_bot
      - POSTGRES_PASSWORD=hashtag_bot
      - POSTGRES_DB=hashtag_db

  redis:
    image: "redis"

  celery:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: celery -A config worker --loglevel=info
    env_file:
      - ./.env
    depends_on:
      - web

  celery-beat:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: celery -A config beat --loglevel=info
    env_file:
      - ./.env
    depends_on:
      - web

volumes:
  postgres_data: