# Generated by Django 5.1.5 on 2025-01-31 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(unique=True, verbose_name='ID беседы в телеграмм')),
                ('name', models.CharField(max_length=255, verbose_name='Название беседы')),
                ('is_superchat', models.BooleanField(default=False, verbose_name='Является суперчатом?')),
                ('parent_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hashtag_bot.chatmodel', verbose_name='Чат, в который пересылать сообщения')),
            ],
        ),
    ]
